version: '3.8'

services:
  api:
    image: sketch-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - sketch-ntw
  db:
    image: postgres
    container_name: sketch-drawing-db
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql
    networks:
      - sketch-ntw

networks:
  sketch-ntw:
    name: sketch